/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apmanager.ui.panels.product;

import com.apmanager.domain.entity.Appliance;
import com.apmanager.domain.entity.Product;
import com.apmanager.domain.entity.ProductBrand;
import com.apmanager.domain.entity.Shelf;
import com.apmanager.service.impl.ProductBrandService;
import com.apmanager.service.impl.ProductService;
import com.apmanager.service.impl.ShelfService;
import com.apmanager.ui.components.Button;
import com.apmanager.ui.components.Table;
import com.apmanager.ui.formaters.EntityWrapper;
import com.apmanager.ui.listeners.ActionListener;
import com.apmanager.ui.listeners.MouseListener;
import com.apmanager.ui.panels.AbstractAdminPanel;
import com.apmanager.ui.panels.productbrand.JDialogEdit;
import com.apmanager.ui.panels.productbrand.JDialogProductBrandEdit;
import com.apmanager.ui.panels.shelf.JDialogShelfEdit;
import com.apmanager.domain.utils.NumberUtils;
import com.towel.el.FieldResolver;
import com.towel.swing.table.ObjectTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author luis
 */
public class JDialogProductEdit extends JDialogEdit<Product, ProductService> {

    private JDialogProductBrandEdit brandEdit;

    private JDialogShelfEdit shelfEdit;

    private JDialogProductApplianceEdit applianceEdit;

    private DefaultComboBoxModel<EntityWrapper<ProductBrand>> brandModel;

    private DefaultComboBoxModel<EntityWrapper<Shelf>> shelfModel;

    private ObjectTableModel<Appliance> applianceModel;

    private ProductBrandService productBrandService;

    private ShelfService shelfService;

    /**
     * Creates new form JDialogProductEdit
     */
    public JDialogProductEdit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        configureListener();
        brandEdit = new JDialogProductBrandEdit(this, true);
        shelfEdit = new JDialogShelfEdit(this, true);
        applianceEdit = new JDialogProductApplianceEdit(this, true);

        //Start services;
        productBrandService = new ProductBrandService();
        brandEdit.setService(productBrandService);

        shelfService = new ShelfService();
        shelfEdit.setService(shelfService);


        brandModel = new DefaultComboBoxModel<>();
        shelfModel = new DefaultComboBoxModel<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabelId = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxProductBrand = new javax.swing.JComboBox();
        jButtonAddBrand = new Button(this);
        jTextFieldName = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButtonAddAppliance = new Button(this);
        jButtonEditAppliance = new Button(this);
        jButtonDelAppliance = new Button(this);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableApplianceResults = new Table();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCode = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldBarCode = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldSellPrice = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldPurchuasePrice = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldQtd = new javax.swing.JTextField();
        jButtonAddShelf = new Button(this);
        jComboBoxShelf = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1AditionalCode = new javax.swing.JLabel();
        jButtonGenerateAditionalCode = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldMinQuantity = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxDiscount = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButtonCancel = new Button(this, KeyEvent.VK_F9);
        jButtonSave = new Button(this, KeyEvent.VK_F8);

        jLabel1.setText("Código:");

        jLabel2.setText("520");

        jLabel3.setText("Nome:");

        jTextField2.setText("General Motors");

        jLabel4.setText("Descrição:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produto");
        setMinimumSize(new java.awt.Dimension(781, 596));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Produto"));

        jLabelId.setText("520");

        jLabel8.setText("Descrição:");

        jLabel7.setText("Nome:");

        jLabel9.setText("Marca:");

        jLabel5.setText("ID:");

        jButtonAddBrand.setText("+");
        jButtonAddBrand.setToolTipText("Adicionar Nova Marca");

        jTextFieldName.setText("General Motors");

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jScrollPane3.setViewportView(jTextAreaDescription);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Aplicações"));

        jButtonAddAppliance.setText("Adicionar Aplicação");

        jButtonEditAppliance.setText("Editar");

        jButtonDelAppliance.setText("Excluir");

        jScrollPane1.setViewportView(jTableApplianceResults);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAddAppliance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditAppliance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelAppliance)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDelAppliance)
                    .addComponent(jButtonEditAppliance)
                    .addComponent(jButtonAddAppliance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel10.setText("Código:");

        jTextFieldCode.setText("FE0051");

        jLabel11.setText("Código de Barras:");

        jTextFieldBarCode.setText("58550002020");

        jLabel12.setText("Preço de Venda:");

        jTextFieldSellPrice.setText("8,55");

        jLabel13.setText("R$");

        jTextFieldPurchuasePrice.setText("6,20");

        jLabel14.setText("R$");

        jLabel15.setText("Preço de Compra:");

        jLabel16.setText("Estoque Atual:");

        jTextFieldQtd.setText("152");

        jButtonAddShelf.setText("+");
        jButtonAddShelf.setToolTipText("Adicionar Nova Prateleira");

        jLabel17.setText("Localização:");

        jLabel18.setText("Código Adicional:");

        jLabel1AditionalCode.setText("0023321");

        jButtonGenerateAditionalCode.setText("Gerar");
        jButtonGenerateAditionalCode.setEnabled(false);

        jLabel20.setText("Estoque Mínimo:");

        jTextFieldMinQuantity.setText("30");

        jLabel21.setText("Desconto Máximo");

        jLabel6.setText("%");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel9)))
                                .addComponent(jLabel11))
                            .addComponent(jLabel12)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jComboBoxProductBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAddBrand))
                            .addComponent(jLabelId)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel1AditionalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonGenerateAditionalCode)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(2, 2, 2)
                                        .addComponent(jTextFieldSellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(194, 194, 194)
                                        .addComponent(jLabel15))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldBarCode, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                            .addComponent(jTextFieldCode))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(2, 2, 2)
                                        .addComponent(jTextFieldPurchuasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jComboBoxShelf, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonAddShelf))
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldMinQuantity, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldQtd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jComboBoxDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelId))
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxProductBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddBrand))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel17)
                    .addComponent(jComboBoxShelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddShelf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldBarCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldMinQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel1AditionalCode)
                    .addComponent(jButtonGenerateAditionalCode)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldSellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldPurchuasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jComboBoxDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonCancel.setText("Cancelar");

        jButtonSave.setText("Salvar");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancel)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonSave))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddAppliance;
    private javax.swing.JButton jButtonAddBrand;
    private javax.swing.JButton jButtonAddShelf;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDelAppliance;
    private javax.swing.JButton jButtonEditAppliance;
    private javax.swing.JButton jButtonGenerateAditionalCode;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox jComboBoxDiscount;
    private javax.swing.JComboBox jComboBoxProductBrand;
    private javax.swing.JComboBox jComboBoxShelf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel1AditionalCode;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableApplianceResults;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldBarCode;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldMinQuantity;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPurchuasePrice;
    private javax.swing.JTextField jTextFieldQtd;
    private javax.swing.JTextField jTextFieldSellPrice;
    // End of variables declaration//GEN-END:variables

    private void configureListener() {
        final JDialogProductEdit dialog = this;

        jButtonAddBrand.addActionListener(new ActionListener(this) {
            @Override
            public void onActionPerformed(ActionEvent e) throws Exception {
                dialog.setEnabled(false);
                ProductBrand brand = new ProductBrand();
                brandEdit.setInstance(brand);
                brandEdit.setVisible(true);
                brandModel.removeAllElements();
                populateBrands();

                // Se a instancia tem marca seleciona ela, se não seleciona a cadastrada.
                if (instance.getBrand() != null) {
                    brandModel.setSelectedItem(new EntityWrapper<>(instance.getBrand()));
                } else {
                    brandModel.setSelectedItem(new EntityWrapper<>(brand));
                }

                dialog.setEnabled(true);
            }
        });

        jButtonAddShelf.addActionListener(new ActionListener(this) {
            @Override
            public void onActionPerformed(ActionEvent e) throws Exception {

                Shelf shelf = new Shelf();
                shelfEdit.setInstance(shelf);
                shelfEdit.setVisible(true);
                populateShelfs();

                // Se a instancia tem marca seleciona ela, se não seleciona a cadastrada.
                if (instance.getShelf() != null) {
                    shelfModel.setSelectedItem(new EntityWrapper<>(instance.getShelf()));
                } else if (shelf.getId() != null) {
                    shelfModel.setSelectedItem(new EntityWrapper<>(shelf));
                }

            }
        });

        jButtonAddAppliance.addActionListener(new ActionListener(this) {
            @Override
            public void onActionPerformed(ActionEvent e) throws Exception {
                dialog.setEnabled(false);
                Appliance a = new Appliance();
                a.setProduct(instance);
                applianceEdit.setInstance(a);
                applianceEdit.setVisible(true);
                a = applianceEdit.getInstance();
                if (a != null) {
                    instance.getAppliances().add(a);
                    populateAppliance();
                }
                dialog.setEnabled(true);
            }
        });

        jButtonEditAppliance.addActionListener(new ActionListener(this) {
            @Override
            public void onActionPerformed(ActionEvent e) throws Exception {
                Appliance ap = getSelectedAppliance();
                if (ap == null) {
                    JOptionPane.showMessageDialog(
                            dialog, "Por favor selecione uma aplicação.",
                            "Atenção", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                applianceEdit.setInstance(ap, true);
                applianceEdit.setVisible(true);
            }
        });

        jTableApplianceResults.addMouseListener(new MouseListener(this) {
            @Override
            public void onMouseRelease(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    Appliance selectedAppliance = ((Table<Appliance>) jTableApplianceResults).getSelected();
                    if (selectedAppliance != null) {
                        applianceEdit.setInstance(selectedAppliance, true);
                        applianceEdit.setVisible(true);
                    }

                }
            }
        });

        jButtonDelAppliance.addActionListener(new ActionListener(this) {
            @Override
            protected void onActionPerformed(ActionEvent e) throws Exception {
                final List<Appliance> vehicleModels = ((Table<Appliance>) jTableApplianceResults).getSelecteds();
                if (AbstractAdminPanel.falseDelete(vehicleModels)) {
                    List<Appliance> data = applianceModel.getData();
                    data.removeAll(vehicleModels);
                    instance.setAppliances(data);
                    populateAppliance();
                }
            }
        });

        jButtonSave.addActionListener(new ActionListener(this) {
            @Override
            public void onActionPerformed(ActionEvent e) throws Exception {
                save();
            }
        });

        jButtonCancel.addActionListener(new ActionListener(this) {
            @Override
            public void onActionPerformed(ActionEvent e) throws Exception {
                dialog.setVisible(false);
            }
        });

        // listener para geração de código adicional
        jButtonGenerateAditionalCode.addActionListener(new ActionListener(this) {
            @Override
            protected void onActionPerformed(ActionEvent e) throws Exception {
                buildObject();
                service.generateNewCode(instance);
                jLabel1AditionalCode.setText(instance.getAdditionalCode());
                jButtonGenerateAditionalCode.setEnabled(false);
            }
        });
    }

    @Override
    protected void restoreFields(Product instance) {

        if (instance.getId() != null) {
            this.jLabelId.setText(String.valueOf(instance.getId()));
        }

        jTextFieldName.setText(instance.getName());

        if (instance.getBrand() != null) {
            brandModel.setSelectedItem(new EntityWrapper<>(instance.getBrand()));
        }

        jTextAreaDescription.setText(instance.getDescription());
        jTextFieldCode.setText(instance.getCode());
        jTextFieldBarCode.setText(instance.getBarcode());

        if (instance.getAdditionalCode() != null && !instance.getAdditionalCode().equals("")) {
            jLabel1AditionalCode.setText(instance.getAdditionalCode());
            jButtonGenerateAditionalCode.setEnabled(false);
        } else {
            jButtonGenerateAditionalCode.setEnabled(true);
        }

        jTextFieldPurchuasePrice.setText(
                NumberUtils.toString(instance.getPurchuasePrice()));
        jTextFieldSellPrice.setText(
                NumberUtils.toString(instance.getSellPrice()));

        if (instance.getShelf() != null) {
            shelfModel.setSelectedItem(new EntityWrapper<>(instance.getShelf()));
        }

        if (instance.getMinQuantity() != null) {
            jTextFieldMinQuantity.setText(String.valueOf(instance.getMinQuantity()));
        }

        if (instance.getQuantity() != null) {
            jTextFieldQtd.setText(String.valueOf(instance.getQuantity()));
        }
        if (instance.getMaxDiscountPercent() != null) {
            jComboBoxDiscount.setSelectedItem(
                    String.valueOf(instance.getMaxDiscountPercent()));
        }
        populateAppliance();

    }

    @Override
    protected Product buildObject() {

        instance.setName(jTextFieldName.getText());

        instance.setBrand(getSelectedBrand());

        instance.setDescription(jTextAreaDescription.getText());
        instance.setCode(jTextFieldCode.getText());
        instance.setBarcode(jTextFieldBarCode.getText());

        instance.setPurchuasePrice(
                NumberUtils.toFloat(jTextFieldPurchuasePrice.getText()));
        instance.setSellPrice(
                NumberUtils.toFloat(jTextFieldSellPrice.getText()));

        instance.setShelf(getSelectedShelf());

        instance.setMinQuantity(NumberUtils.toInteger(jTextFieldMinQuantity.getText()));

        instance.setQuantity(NumberUtils.toInteger(jTextFieldQtd.getText()));

        instance.setMaxDiscountPercent(Integer.valueOf((String) jComboBoxDiscount.getSelectedItem()));

        restoreAppliance();

        return instance;
    }

    @Override
    protected void clear() {

        this.brandEdit.clear();
        this.brandModel.removeAllElements();
        shelfModel.removeAllElements();
        this.jLabelId.setText("");
        jTextFieldName.setText("");

        jTextAreaDescription.setText("");
        jTextFieldCode.setText("");
        jTextFieldBarCode.setText("");

        jLabel1AditionalCode.setText("");
        jButtonGenerateAditionalCode.setEnabled(false);
        jComboBoxDiscount.getModel().setSelectedItem(String.valueOf(0f));

        jTextFieldMinQuantity.setText("");
        jTextFieldQtd.setText("");

        populateComboDiscounts();
        populateBrands();
        populateShelfs();

    }

    private void populateBrands() {
        List<ProductBrand> brands = productBrandService.search("");

        try {
            EntityWrapper<ProductBrand> wrapper = EntityWrapper.createEmpty(ProductBrand.class);
            brandModel.addElement(wrapper);
        } catch (InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(JDialogProductEdit.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (ProductBrand b : brands) {
            brandModel.addElement(new EntityWrapper<>(b));
        }
        jComboBoxProductBrand.setModel(brandModel);
    }

    private void populateComboDiscounts() {
        int i = 0;
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        while (i < 100) {
            model.addElement(String.valueOf(i));
            i = i + 5;
        }

        jComboBoxDiscount.setModel(model);

    }

    private void populateShelfs() {
        shelfModel.removeAllElements();
        try {
            EntityWrapper<Shelf> wrapper = EntityWrapper.createEmpty(Shelf.class);
            shelfModel.addElement(wrapper);
        } catch (InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(JDialogProductEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
        List<Shelf> shelfs = shelfService.search("");
        for (Shelf shelf : shelfs) {
            shelfModel.addElement(new EntityWrapper<>(shelf));
        }
        jComboBoxShelf.setModel(shelfModel);
    }

    private void populateAppliance() {

        FieldResolver vehicle =
                new FieldResolver(Appliance.class, "model.vehicle.name", "Veículo");
        FieldResolver model =
                new FieldResolver(Appliance.class, "model.name", "Modelo");
        FieldResolver year =
                new FieldResolver(Appliance.class, "model.year", "Ano");

        applianceModel =
                new ObjectTableModel<>(new FieldResolver[]{vehicle, model, year});
        
        applianceModel.setData(instance.getAppliances());
        jTableApplianceResults.setModel(applianceModel);

    }

    private void restoreAppliance() {
        instance.setAppliances(applianceModel.getData());
    }

    private ProductBrand getSelectedBrand() {
        EntityWrapper<ProductBrand> wrapper =
                (EntityWrapper<ProductBrand>) brandModel.getSelectedItem();

        if (wrapper == null || wrapper.isFake()) {
            return null;
        }

        return wrapper.getEntity();
    }

    private Appliance getSelectedAppliance() {
        Appliance a = ((Table<Appliance>) jTableApplianceResults).getSelected();
        return a;
    }

    private Shelf getSelectedShelf() {
        EntityWrapper<Shelf> wrapper = (EntityWrapper<Shelf>) shelfModel.getSelectedItem();

        if (wrapper == null || wrapper.isFake()) {
            return null;
        }

        return wrapper.getEntity();
    }
}
