/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apmanager.ui.panels;

import com.apmanager.domain.entity.Sale;
import com.apmanager.ui.listeners.ActionListener;
import com.apmanager.ui.listeners.FocusListener;
import com.apmanager.ui.listeners.KeyListener;
import com.apmanager.ui.listeners.MouseListener;
import com.apmanager.ui.utils.NumberUtils;
import java.awt.event.ActionEvent;
import java.awt.event.FocusEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;

/**
 *
 * @author luis
 */
public class JDialogCloseSale extends javax.swing.JDialog {

    private Sale current;

    private boolean canceled = false;

    /**
     * Creates new form JDialogCloseSale
     */
    public JDialogCloseSale(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        configureListener();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelTotalValue = new javax.swing.JLabel();
        jLabelQtd = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabelSimbol = new javax.swing.JLabel();
        jButtonCloseSale = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Valor total:");

        jLabel2.setText("Quantidade de produtos:");

        jLabelTotalValue.setText("35,60");
        jLabelTotalValue.setMaximumSize(new java.awt.Dimension(58, 205));
        jLabelTotalValue.setMinimumSize(new java.awt.Dimension(58, 19));
        jLabelTotalValue.setPreferredSize(new java.awt.Dimension(58, 19));

        jLabelQtd.setText("7");

        jTextField1.setText("35,60");

        jLabelSimbol.setText("R$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelQtd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelSimbol, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(101, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSimbol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelQtd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonCloseSale.setText("Fechar Venda");

        jButtonCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCloseSale)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCloseSale)
                    .addComponent(jButtonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCloseSale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelQtd;
    private javax.swing.JLabel jLabelSimbol;
    private javax.swing.JLabel jLabelTotalValue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void configureListener() {
        final JDialogCloseSale dialog = this;
        jLabelTotalValue.addMouseListener(new MouseListener(dialog) {
            @Override
            public void onMouseRelease(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    setEditing(true);
                }
            }
        });

        jTextField1.addFocusListener(new FocusListener(dialog) {
            @Override
            public void onBlur(FocusEvent e) throws Exception {
                setEditing(false);
            }
        });
        jTextField1.addKeyListener(new KeyListener(dialog) {
            @Override
            public void onKeyRelease(KeyEvent e) {
                if(e.getKeyCode() == KeyEvent.VK_ESCAPE){
                    setEditing(false);
                }
            }
        });
        this.addMouseListener(new MouseListener(dialog){
            @Override
            public void onMouseClick(MouseEvent e) {
                if(!e.getSource().equals(jTextField1)){
                    setEditing(false);
                }
            }
            
        });
        
        jButtonCancelar.addActionListener(new ActionListener(this) {
            @Override
            protected void onActionPerformed(ActionEvent e) throws Exception {
                dialog.setVisible(false);
            }
        });
        
        jButtonCloseSale.addActionListener(new ActionListener(dialog) {
            @Override
            protected void onActionPerformed(ActionEvent e) throws Exception {
                canceled = false;
                dialog.setVisible(false);
            }
        });
    }

    private void setEditing(boolean editing) {
        jLabelTotalValue.setVisible(!editing);
        jTextField1.setVisible(editing);
        if(!editing){
            current.setTotal(NumberUtils.toFloat(jTextField1.getText()));
            jLabelTotalValue.setText(jTextField1.getText());
        }
    }

    public boolean isCanceled() {
        return canceled;
    }

    private void loadValues() {
        String value = NumberUtils.toString(current.getTotal());
        this.jLabelTotalValue.setText(value);
        this.jTextField1.setText(value);
        jLabelQtd.setText(String.valueOf(current.getProductQuantity()));
    }
    
    public void setSale(Sale sale){
        current = sale;
        loadValues();
        setEditing(false);
    }
}
