/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apmanager.ui.panels;

import com.apmanager.domain.entity.Sale;
import com.apmanager.domain.exceptions.OutOfDiscountException;
import com.apmanager.service.impl.SaleService;
import com.apmanager.ui.components.Button;
import com.apmanager.ui.components.abstractcomps.JDialogEscape;
import com.apmanager.ui.listeners.ActionListener;
import com.apmanager.ui.listeners.FocusListener;
import com.apmanager.ui.listeners.KeyListener;
import com.apmanager.ui.listeners.MouseListener;
import com.apmanager.ui.utils.NumberUtils;
import java.awt.event.ActionEvent;
import java.awt.event.FocusEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author luis
 */
public class JDialogCloseSale extends JDialogEscape {

    private SaleService service;

    private Sale current;

    private boolean canceled = false;

    private Float selectedValue;

    /**
     * Creates new form JDialogCloseSale
     */
    public JDialogCloseSale(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        configureListener();
        service = new SaleService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelTotalValue = new javax.swing.JLabel();
        jLabelQtd = new javax.swing.JLabel();
        jTextFieldNewValue = new javax.swing.JTextField();
        jLabelSimbol = new javax.swing.JLabel();
        jButtonCloseSale = new Button(this, KeyEvent.VK_F6);
        jButtonCancelar = new Button(this, KeyEvent.VK_F8);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Valor total:");

        jLabel2.setText("Quantidade de produtos:");

        jLabelTotalValue.setText("35,60");
        jLabelTotalValue.setMaximumSize(new java.awt.Dimension(58, 205));
        jLabelTotalValue.setMinimumSize(new java.awt.Dimension(58, 19));
        jLabelTotalValue.setPreferredSize(new java.awt.Dimension(58, 19));

        jLabelQtd.setText("7");

        jTextFieldNewValue.setText("35,60");

        jLabelSimbol.setText("R$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelQtd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelSimbol, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNewValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(101, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNewValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSimbol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelQtd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonCloseSale.setText("Fechar Venda");

        jButtonCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCloseSale)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCloseSale)
                    .addComponent(jButtonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCloseSale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelQtd;
    private javax.swing.JLabel jLabelSimbol;
    private javax.swing.JLabel jLabelTotalValue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldNewValue;
    // End of variables declaration//GEN-END:variables

    private void configureListener() {

        final JDialogCloseSale dialog = this;

        jLabelTotalValue.addMouseListener(new MouseListener(dialog) {
            @Override
            public void onMouseRelease(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    setEditing(true);
                }
            }
        });

        jTextFieldNewValue.addFocusListener(new FocusListener(dialog) {
            @Override
            public void onBlur(FocusEvent e) throws Exception {
                setEditing(false);
            }
        });

        jTextFieldNewValue.addKeyListener(new KeyListener(dialog) {
            @Override
            public void onKeyRelease(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                    setEditing(false);
                } else if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    setNewValue();
                    setEditing(false);
                }
            }
        });

        this.addMouseListener(new MouseListener(dialog) {
            @Override
            public void onMouseClick(MouseEvent e) {
                if (!e.getSource().equals(jTextFieldNewValue)) {
                    setEditing(false);
                }
            }
        });

        jButtonCancelar.addActionListener(new ActionListener(this) {
            @Override
            protected void onActionPerformed(ActionEvent e) throws Exception {
                dialog.setVisible(false);
            }
        });

        jButtonCloseSale.addActionListener(new ActionListener(dialog) {
            @Override
            protected void onActionPerformed(ActionEvent e) throws Exception {
                canceled = false;
                current.setTotal(selectedValue);
                try {
                    service.closeSale(current);
                    dialog.setVisible(false);
                } catch (OutOfDiscountException ex) {
                    showDiscountInfo(ex);
                }
            }
        });
    }

    private void setEditing(boolean editing) {
        jLabelTotalValue.setVisible(!editing);
        jTextFieldNewValue.setVisible(editing);
        jTextFieldNewValue.setText(jLabelTotalValue.getText());

    }

    public boolean isCanceled() {
        return canceled;
    }

    private void loadValues() {
        String value = NumberUtils.toString(current.getTotal());
        this.jLabelTotalValue.setText(value);
        this.jTextFieldNewValue.setText(value);
        jLabelQtd.setText(String.valueOf(current.getProductQuantity()));
    }

    public void setSale(Sale sale) {
        current = sale;
        selectedValue = current.getTotal();
        loadValues();
        setEditing(false);
    }

    private void setNewValue() {
        try {

            selectedValue = NumberUtils.toFloat(jTextFieldNewValue.getText());
            service.checkTotal(current, selectedValue);
            jLabelTotalValue.setText(jTextFieldNewValue.getText());

        } catch (OutOfDiscountException ex) {
            showDiscountInfo(ex);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Valor inválido");
        }
    }

    private void showDiscountInfo(OutOfDiscountException ex) {
        JOptionPane.showMessageDialog(this, "Valor selecionado está abaixo do valor de desconto máximo\n"
                + "Valor do desconto máximo:\t\tR$ " + NumberUtils.toString(ex.getMinValue()) + "\n"
                + "Valor do percentual máximo de desconto:\t" + ex.getMaxDiscountPercent() + "%\n"
                + "Valor do percentual aplicado:\t\t" + ex.getCurrentDiscoutPercent() + "%",
                "Atenção", JOptionPane.WARNING_MESSAGE);
    }
}
